version: '3'
services:
  # nginx and certbot configs adapted from https://github.com/wmnnd/nginx-certbot/blob/master/docker-compose.yml
  nginx:
    image: ${NGINX_IMAGE}
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd/:/conf/htpasswd/:ro
      - ./html/:/usr/share/nginx/html/:ro
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $$${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    # The init script starts only nginx, which requires the upstreams to be started, so we define this dependency here
    depends_on:
    %{ for name, instance_info in INSTANCES }
    - wetty-${name}
    %{ endfor }
  certbot:
    image: ${CERTBOT_IMAGE}
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $$${!}; done;'"
  %{ for name, instance_info in INSTANCES }
  wetty-${name}:
    image: ${WETTY_IMAGE}
    volumes:
      - ./keys/${instance_info["student"]}:/keys/key
    command: --ssh-host=${instance_info["ip"]} --ssh-auth=publickey --ssh-user=student --ssh-key /keys/key --base=/${name}
  %{ endfor }
